services:
#  postgres:
#    image: pgvector/pgvector:pg17
#    container_name: postgres_pgvector
#    environment:
#      POSTGRES_DB: ai_documents_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: unless-stopped

  backend-fastapi:
    container_name: auth0-secure-agent-backend-1
    build:
      context: .
      dockerfile: ./backend-fastapi/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    networks:
      - applications-networks
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - backend-langgraphapi

  backend-langgraphapi:
    container_name: auth0-secure-agent-langgraph-api-1
    build:
      context: .
      dockerfile: ./backend-langgraphapi/Dockerfile.langgraph
    ports:
      - "5436:5436"
    env_file:
      - .env.docker
    networks:
      - applications-networks
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    container_name: auth0-secure-agent-frontend-1
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend-fastapi
      - backend-langgraphapi
    networks:
      - applications-networks
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres_data:

networks:
  applications-networks:
    name: applications-networks
    external: true
