FROM python:3.13-slim

WORKDIR /app

RUN pip install langgraph-api langgraph-cli langchain_google_genai pydantic-settings

RUN mkdir -p /app/app /app/app/agents /app/app/agents/mcp /app/app/core /app/app/agents/tools

COPY langgraph.json /app/

COPY gcloud-credentials.json /app/gcloud-credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-credentials.json

COPY pyproject.toml /app/pyproject.toml

COPY app/agents/assistant0.py /app/app/agents/assistant0.py

COPY app/main.py /app/app/main.py

COPY app/core/config.py /app/app/core/config.py

COPY app/agents/tools/project_tasks_list.json /app/app/agents/tools/project_tasks_list.json

COPY app/agents/tools/project_tasks.py /app/app/agents/tools/project_tasks.py

COPY app/agents/tools/user_info.py /app/app/agents/tools/user_info.py

CMD ["langgraph", "dev",  "--config", "./langgraph.json", "--host", "0.0.0.0", "--port", "5436", "--allow-blocking", "--no-browser"]
