FROM python:3.13-slim

WORKDIR /app

# Copy and install shared code first (layer caching)
COPY common/ ./common/
RUN pip install --no-cache-dir ./common/

# Copy component code and deps
COPY backend-langgraphapi/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend-langgraphapi/ .

RUN mkdir -p ./app ./app/agents ./app/agents/mcp ./app/core ./app/agents/tools

COPY backend-langgraphapi/langgraph.json .

COPY backend-langgraphapi/gcloud-credentials.json .
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-credentials.json

COPY backend-langgraphapi/pyproject.toml .

#COPY app/agents/assistant0.py /app/app/agents/assistant0.py

#COPY app/main.py /app/app/main.py

#COPY app/core/config.py /app/app/core/config.py

#COPY app/agents/tools/project_tasks_list.json /app/app/agents/tools/project_tasks_list.json

#COPY app/agents/tools/project_tasks.py /app/app/agents/tools/project_tasks.py

#COPY app/agents/tools/user_info.py /app/app/agents/tools/user_info.py

EXPOSE 5436

CMD ["langgraph", "dev",  "--config", "./langgraph.json", "--host", "0.0.0.0", "--port", "5436", "--allow-blocking", "--no-browser"]
